var base__ = "https://voxelprismatic.github.io/priz.md/out/";
var head__ = document.getElementById("priz_script");
var script__ = document.createElement("script");
script__.src = base__ + "md.min.js";
script__.type = "text/javascript";
head__.after(script__);
var css__ = document.createElement("link");
css__.rel = "stylesheet";
css__.type = "text/css";
css__.href = base__ + "style.lite.min.css";
head__.after(css__);
delete css__;
delete script__;
delete base__;
delete head__;
